# Generated by Django 4.1.1 on 2022-10-05 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Participants',
            field=models.ManyToManyField(blank=True, related_name='Participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
