# Generated by Django 4.1.1 on 2022-10-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Participants',
            new_name='participants',
        ),
    ]
