# Generated by Django 4.1.1 on 2022-10-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_participants_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
